### ISSUE TITLE
Feature Request: Accompanying Button

### ISSUE THREAD

**Issue by zayKenyon** [gutentag2012/obsidian-plugin-clear-todos#1]
Hi! So glad you made this plugin, it's very useful 🫶.

Would it be possible to also get an accompanying button to activate the command? I use a similar plugin, [claremacrae/reveal-active-file-button-plugin](https://github.com/claremacrae/reveal-active-file-button-plugin) which is a similar system: one command, one button, I have attached an image on what this looks like in practice.

![image](https://github.com/user-attachments/assets/906b1c25-e7f5-48a2-b8d3-ceccb0a6dcdd)

I am happy to give this a shot and submit a PR if this would be an acceptable addition!

**Comment by gutentag2012** [comment]
Yes sounds like a great idea, feel free to create a PR 😄

**Comment by zayKenyon** [comment]
Closed in f0e3226
