### ISSUE TITLE
New Update Unrecognised by Obsidian

### ISSUE THREAD

**Issue by zayKenyon** [gutentag2012/obsidian-plugin-clear-todos#4]
Thanks for releasing the buttons!

Tried to install the new update, Obsidian recognises that a new update was released (11 hours ago), but won't let me one-click update? 🤔

It looks like you've got your tags right, this isn't the first update the plugin has released. In any case, it might be worth following [this ](https://docs.obsidian.md/Plugins/Releasing/Release+your+plugin+with+GitHub+Actions)Obsidian guide?

I can install it manually, but thought I would drop an issue in-case it goes unnoticed.

![image](https://github.com/user-attachments/assets/65ed6121-7aa9-4208-8149-ffd0d04e6a26)

**Comment by gutentag2012** [comment]
Oh thank you I will take a took at this 👍

**Comment by gutentag2012** [comment]
Seems like it is fixed now. I forgot to push the updated version in the manifest
